### ISSUE TITLE
Supergroup ID is not saved correctly

### ISSUE THREAD

**Issue by OctoNezd** [mastercake10/TelegramChat#18]
Hi!
Installed plugin on my server, sent message of bot token, send link code in group, and messages don't arrive in group. 

Checked plugins/TelegramChat/data.json - it has invalid chat ID in key chat_ids: -925237114, while the correct ID is -1001652617082
![image](https://user-images.githubusercontent.com/15308404/147380742-5e9ad6cb-7b9a-40db-addd-cdffdf57aa7a.png)

Edited chat id to be correct, plugin crashed during startup:
```
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 INFO]: [TelegramChat] Enabling TelegramChat v1.0.17-SNAPSHOT*
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]: java.io.StreamCorruptedException: invalid stream header: 7B22746F
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:963)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:397)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at telegramchat-1.0.17-SNAPSHOT.jar//de.Linus122.TelegramChat.TelegramChat.onEnable(TelegramChat.java:74)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 WARN]:         at java.base/java.lang.Thread.run(Thread.java:833)
Dec 25 08:18:30 vps-9ccc607e run.sh[138084]: [08:18:30 INFO]: [TelegramChat] Converted old data.yml
```

I assume it's integer overflow, cause minimum value of Integer in java is -2147483648?

**Comment by iCaitlyn** [comment]
Based off other Telegram bots, it seems the best way to fix this is to simply use long and Long instead of int and Integer, whenever it has to do with user IDs and chat IDs
